### ISSUE TITLE
Can't build, That's literally it

### ISSUE THREAD

**Issue by SonicTheHedgeHog64** [N64Recomp/N64Recomp#106]
![image](https://github.com/user-attachments/assets/aff8c84c-0716-4725-a457-b7c82ce646df)

toml config:
(
# Config file for Peach's Fury Recompilation

[input]
# Paths are relative to the location of this config file.
entrypoint = 0x80000400
output_func_path = "RecompiledFuncs"
elf_path = "sm64.us.f3dex2.elf"
)

**Comment by Mr-Wiseguy** [comment]
Please refer to existing issues asking about the entrypoint.
