### ISSUE TITLE
Unhandled instruction: tlbp

### ISSUE THREAD

**Issue by codingzerotohero** [N64Recomp/N64Recomp#108]
Hi! I’m using an elf file from building the Banjo Kazooie US V1.0 decomp project, tried using the N64Recomp tool with the elf file - and getting this unhandled instruction error.

Also got unhandled mfc0 and mtc0 cop0 (EntryHi 10 value) but managed to implement the handling for it myself - to be fair I’m not sure if simply adding cop0_entryhi_write/read for mfc0 and mtc0 cases will work when trying to use the func files at a later stage, but it has at least allowed the N64Recomp program to progress further - as those were the first errors.

The function is boot___osProbeTLB.
If I understand this project correctly - can I simply write the C equivalent of this function myself, and provide it in a manual_funcs file which I then point to in the .toml file or am I on the wrong track here?

I have to admit I’m completely fresh in the decomp/recomping of N64 games scene but I got very curious about these things after finally getting a 100% run on the Majoras Mask recomp, 20 years after trying the game for the first time.

**Comment by codingzerotohero** [comment]
Heres a screenshot of the result of running `readelf -s banjo.us.v10.elf | grep boot___osProbeTLB`
![result](https://github.com/user-attachments/assets/219a1268-ba18-445b-83d5-ddd43ba28621)

**Comment by codingzerotohero** [comment]
objdump gives me this:

`mips-linux-gnu-objdump -d banjo.us.v10.elf | grep -A20 80003bd0`

`800030b4:       0c000ef4        jal     80003bd0 <boot___osProbeTLB>
800030b8:       8fa40018        lw      a0,24(sp)
800030bc:       8fbf0014        lw      ra,20(sp)
800030c0:       27bd0018        addiu   sp,sp,24
800030c4:       03e00008        jr      ra
800030c8:       00000000        nop
800030cc:       00000000        nop

800030d0 <boot___osSiDeviceBusy>:
800030d0:       3c0ea480        lui     t6,0xa480
800030d4:       8dc40018        lw      a0,24(t6)
800030d8:       27bdfff8        addiu   sp,sp,-8
800030dc:       308f0003        andi    t7,a0,0x3
800030e0:       11e00003        beqz    t7,800030f0 <boot___osSiDeviceBusy+0x20>
800030e4:       00000000        nop
800030e8:       10000002        b       800030f4 <boot___osSiDeviceBusy+0x24>
800030ec:       24020001        li      v0,1
800030f0:       00001025        move    v0,zero
800030f4:       03e00008        jr      ra
800030f8:       27bd0008        addiu   sp,sp,8
800030fc:       00000000        nop
--
80003bd0 <boot___osProbeTLB>:
80003bd0:       40085000        mfc0    t0,c0_entryhi
80003bd4:       310900ff        andi    t1,t0,0xff
80003bd8:       2401e000        li      at,-8192
80003bdc:       00815024        and     t2,a0,at
80003be0:       012a4825        or      t1,t1,t2
80003be4:       40895000        mtc0    t1,c0_entryhi
        ...
80003bf4:       42000008        tlbp
        ...
80003c00:       400b0000        mfc0    t3,c0_index
80003c04:       3c018000        lui     at,0x8000
80003c08:       01615824        and     t3,t3,at
80003c0c:       1560001a        bnez    t3,80003c78 <boot___osProbeTLB+0xa8>
80003c10:       00000000        nop
80003c14:       42000001        tlbr
        ...
80003c24:       400b2800        mfc0    t3,c0_pagemask
80003c28:       216b2000        addi    t3,t3,8192
80003c2c:       000b5842        srl     t3,t3,0x1
80003c30:       01646024        and     t4,t3,a0
80003c34:       15800004        bnez    t4,80003c48 <boot___osProbeTLB+0x78>`

**Comment by Mr-Wiseguy** [comment]
The `boot_` prefixed libultra functions in the BK decompilation need to be handled just like the normal libultra functions are. Each function either needs to be ignored (like this one) or reimplemented (like the boot raw PI DMA function). It's a quirk of the build system that BK decomp has due to needing two copies of libultra in it, which happen to be familiar with since I was the one who set it up. Unfortunately I don't have much free time at the moment, so I won't be able to go through the exact steps to deal with this problem.

With that said I'm already working on a BK recomp on the backburner; it may be a while before I get time to more actively work on it. Don't let that stop you if you're doing this for fun of course, but I figured it'd be good to let you know.

**Comment by codingzerotohero** [comment]
Ah ok, so they should all be ignored. Thanks. 

However after ignoring them as they came up, this one appeared: func_8026A2E0
readelf gives me this:

`9090: 8026a2e0  1348 FUNC    GLOBAL DEFAULT   12 func_8026A2E0` 

I don't suppose that one is also part of the functions that should be ignored? I haven't looked into its content yet but it's an `mfc0` value exception `13`.

**Comment by codingzerotohero** [comment]
As far as `func_8026A824` goes - it was NOT due to anything related to mfc0 - it's actually this:
`unable to find jump table for 'jr $s2' at 0x8026A8D0 in func_8026A824`

**Comment by Mr-Wiseguy** [comment]
`func_8026A2E0` and `func_8026A824` are libultra functions with missing names, they can be ignored since they're part of the thread scheduler which is reimplemented in the runtime.

**Comment by codingzerotohero** [comment]
Ok, thanks! Closing the issue.
