### ISSUE TITLE
Add a mode to the recompiler where it can accept a symbol definition file instead of an elf file

### ISSUE THREAD

**Issue by Mr-Wiseguy** [N64Recomp/N64Recomp#13]
This will significantly simplify the build process of recompilations, since it will bypass the requirement to build a decompilation/disassembly before building a recompilation. This can also be used in patch recompilation so that it can handle relocations automatically.

The symbol definition file will need to include section ROM offsets and base VRAM addresses, symbol parent sections and VRAM addresses, and sizes for function symbols. It could also accept file boundaries so the recompiler can emit multiple functions per file, which would speed up configure and build steps for recompilations.

**Comment by PaulGrandperrin** [comment]
Hi, thanks for this great project! 
I'm trying to package this for NixOS, so I'm trying to automate the whole building.

I'm at the stage where Zelda64Recomp is only missing the `RecompiledFuncs` and I have the `N64Recompiler` and the ROM ready.

When stracing `N64Recomp us.rev1.toml`, I see that it's looking for a `mm.us.rev1.elf` file.

I'm not sure I understand what this file is supposed to be.

Could you give a few more details? Thanks!

**Comment by Mr-Wiseguy** [comment]
Implemented in ba4aede49c9a5302ecfc1fa599f7acc3925042f9
