### ISSUE TITLE
Hook insertion

### ISSUE THREAD

**Issue by Mr-Wiseguy** [N64Recomp/N64Recomp#3]
Building on top of #1, a mechanism is required to insert function call hooks into the recompilation output. This will be mainly used to add overlay load hooks into games.

Hooks should provide a function name and the VRAM address of the instruction to insert the hook before. Hooks meant to be placed at the end of a function can provide the VRAM value of the instruction following the last one in the function. Hooks that omit an instruction VRAM address will be inserted at the start of a function, which will likely be the most common use case for hooks.

**Comment by AngheloAlf** [comment]
Addressed by #73
