### ISSUE TITLE
[Question] What if a game doesn't have any decompiled source?

### ISSUE THREAD

**Issue by lucmsilva651** [N64Recomp/N64Recomp#32]
Yea, sorry for bothering any of you guys, but I need to ask a question. I'm interested to port a game with this tool, and the game itself doesn't have any progress or anything related to decompilation yet.

Do I need to decompile the game myself? If that is, it is a really dificult process or nah?

Ahm, and the game in question is AeroGauge, which I already reserved a repository and everything but I just need to know this to continue, as I said before, the game itself doesn't have any progress or anything related to decompilation yet.

(I am dumb and posted this issue on other repo, as [this issue](https://github.com/Mr-Wiseguy/Zelda64Recomp/issues/131) lmfaoo)

**Comment by Rainchus** [comment]
You don't actually need to decompile anything. You do, however, need to get a general idea of how the ROM is structured. Knowing where the functions are that the game uses to dma data from ROM to RAM, as well as any kind of overlays and how the game loads those will need to be figured out. Using n64splat and setting up a decomp project (which can really just be a disassembly) and then splitting out the data correctly to then be built into an elf should work with N64Recomp.

**Comment by lucmsilva651** [comment]
Ty for the response. I will leave this ticket open by now in case of someone can leave more info on how can I do this.
