### ISSUE TITLE
[Feature Request] Recomp to native GameCube ISO

### ISSUE THREAD

**Issue by TriVoxel** [N64Recomp/N64Recomp#46]
A modded GameCube can barely manage to run most N64 games at 20 FPS, if at all. Imagine how cool it would be if we could recompile N64 games to native GameCube games for playing on a modded GameCube. I know this is a wild ask but, it would be sick! Maybe it could be done by including the GC homebrew dev stuff with this project and putting it in a Docker image? IDK, I can dream...

**Comment by miqumi** [comment]
The project just outputs c code. It's upto the person who is porting the game to choose the platform it'd be on.

**Comment by AngheloAlf** [comment]
It is true that the recompiling process could be used to target platforms other than PC, but to do that you would need to rewrite a big chunk of the runtime used by recomp.
For example, the graphic renderer used by the Zelda64Recomp uses and takes advantage of the modern graphic APIs like DirectX 12 and Vulkan, neither of which are available on most platforms, specially on old ones like the Gamecube.
On the other hand, the SDK reimplementation (the runtime) would need to be adapted to a whole new system, possibly having  to rewrite a big chunk of it.

So the recompilation process offered by this repository can be used as a base for targeting other platforms, it would involve so much work that it would become its own whole new project.
