### ISSUE TITLE
missing .dll files?

### ISSUE THREAD

**Issue by zazasmeller** [N64Recomp/N64Recomp#51]
when i buildt and ran n64recomp, it said libgcc_s_seh-1.dll and libstdc++-6.dll are missing? it said reinstalling the program may fix this but i tried and it gives me the same error
![Screenshot 2024-05-16 182136](https://github.com/Mr-Wiseguy/N64Recomp/assets/132506054/23938807-3d95-4aea-be03-4a25065d2dd4)
![Screenshot 2024-05-16 182115](https://github.com/Mr-Wiseguy/N64Recomp/assets/132506054/1dcbf627-37a9-45f9-929e-f4f000fce277)

**Comment by notwa** [comment]
AFAIK those are MSYS2 DLLs; you either need to copy them into the build directory, or choose a different C++ compiler.

Assuming you've installed MSYS2 to C:\msys64, you can typically find those DLLs here: C:\msys64\mingw64\bin

You will also need to copy `libwinpthread-1.dll` while you're at it.

**Comment by zazasmeller** [comment]
i did it but, when i open the .exe it opens, then closes very quickly, i think its a command type of thing where you type commands but i dont know which ones
