### ISSUE TITLE
Error While Building

### ISSUE THREAD

**Issue by AwayCoast23465** [N64Recomp/N64Recomp#64]
I get this error when trying to build;

ld: open() failed, errno=21 for 'N64Recomp'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/N64Recomp.dir/build.make:147: N64Recomp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/N64Recomp.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**Comment by AngheloAlf** [comment]
It is hard to diagnose this kind of issue without any more info.
What platform are you on? What OS are you on?
How did you clone the repo? Did you remembered to do a recursive clone?
What commands did you use when trying to build the repo?

**Comment by AwayCoast23465** [comment]
Sorry i fixed my issue i forgot to make a build folder im going to close the issue
