### ISSUE TITLE
Anyone try sf64?

### ISSUE THREAD

**Issue by michaelachrisco** [N64Recomp/N64Recomp#66]
I was able to get https://github.com/sonicdcer/sf64 decompiled and working as per their instructions. Thought it would be a good place, since the build folder generates the .elf file and spits out the uncompressed file at the end. 

I was able to compile this project pretty easy, but ran into a snag when it came to the elf file (go figure). Im new to all this so maybe im doing this wrong here. 
End result of sf64:
starfox64.us.rev1.elf
starfox64.us.rev1.map
starfox64.us.rev1.uncompressed.z64
starfox64.us.rev1.z64

Created a simple toml:
```
[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
# relocatable_sections_path = "overlays.us.rev1.txt"
symbols_file_path = "starfox64.us.rev1.elf"
rom_file_path = "starfox64.us.rev1.uncompressed.z64"
```

```
Syntax error parsing toml: starfox64.us.rev1.elf (line 1, column 1):
Error while parsing root table: expected keys, tables, whitespace or comments, saw '\u007F'
Failed to load symbols file
```

**Comment by michaelachrisco** [comment]
> "symbols_file_path" isn't for the elf, it's used for a file generated from it, in the MM recomp it's named "us.rev1.syms.toml" don't know how you actually make that file

Interesting, ill see if I can find something similar. I just ran through the instructions on the other project and it generated the files. `make init` basically just took over from there (they did an awesome job). Theres some source code they provide in the git repo.

**Comment by sonicdcer** [comment]
![image](https://github.com/N64Recomp/N64Recomp/assets/96613413/4ba3fe4b-ba22-4092-bd9e-65eaf8ed191a)
I did, but it seems N64Recomp is not yet ready for it because it doesn't support overlapping VRAM addresses for overlays.

**Comment by michaelachrisco** [comment]
Thanks for getting that far. Dang ok. Well it was worth a try. Thanks again for the work on the project, I had no issues getting the uncompiled code to compile. 

What did you do to get the elf/other files (toml) up and running?

**Comment by michaelachrisco** [comment]
Since this isn't really an "issue" anymore, im going to close this out.

**Comment by arefdsg** [comment]
cool to see it working with another game

**Comment by arefdsg** [comment]
> Thanks for getting that far. Dang ok. Well it was worth a try. Thanks again for the work on the project, I had no issues getting the uncompiled code to compile.
> 
> What did you do to get the elf/other files (toml) up and running?
change "symbol_file_path" to "elf_path"

**Comment by sonicdcer** [comment]
Contact me on discord and maybe i can show you guys what i've got so far, maybe you can pick it up from there.
