### ISSUE TITLE
Makefile issue?

### ISSUE THREAD

**Issue by CCIGAMES** [N64Recomp/N64Recomp#67]
C:\Program Files\Microsoft Visual Studio\2022\Community>cmake --build C:\Users\charl\N64Recomp\build
make: Makefile: No such file or directory
make: *** No rule to make target 'Makefile'.  Stop.

**Comment by AngheloAlf** [comment]
Did you configure `cmake` first by using the `-B` flag?

Also, since you are on Windows and have Visual Studio then it is recommended to use Visual Studio for building

**Comment by CCIGAMES** [comment]
idk what i did, followed someones git instructions and used copilot when i got errors, how can i build with just VS?

**Comment by AngheloAlf** [comment]
We can't help you if not even yourself know what you did to setup the repository.

Personally I'm not a Windows user so I can't give you instructions on how to use Visual Studio. I suggest to learn how to use this kind of development tools (Visual Studio, cmake, C++, etc) before trying to use a project like this.

**Comment by CCIGAMES** [comment]
the main issue is that it cant find a makefile

**Comment by AngheloAlf** [comment]
cmake on Windows does not use makefiles by deafult, meaning that you have a weird setup. So you have to try to remember what you did before we could try to help.

Make sure you are using buildtools installed from the Visual Studio Installer and not from other sources like msys or cygwin, those build systems are not supported here.

**Comment by molina95** [comment]
Hello, Sorry for any inconvenience this may not be the proper place to aks this but I do want to understand how to use this recomp tool to try and make a port for megaman legends or megaman 64 as it is called, I only know basic C and C++.
I understand there is previous knowledge that I should have before even trying to do something like this, I really don't know where to begin other than simply read this projects documentation and go from there, so I wanted to ask someone about recommended readings or resources that would help me.
Thanks in advance for any assistance given.

**Comment by Mr-Wiseguy** [comment]
You can build with VS by just opening the folder via File -> Open -> Folder in a recent enough version of Visual Studio 2022, which is how I work on this project myself. If you have the CMake tooling installed (make sure you've done so in the Visual Studio installer), then the Visual Studio CMake integration will automatically set everything up for building.

**Comment by CCIGAMES** [comment]
cheers, now ik why they call you mr wiseguy
