### ISSUE TITLE
Im having trouble building this

### ISSUE THREAD

**Issue by GamingUnleashed** [N64Recomp/N64Recomp#91]
Can you teach me

**Comment by LittlestCube** [comment]
![teachyoutheways](https://github.com/user-attachments/assets/acf630d2-2fd1-4555-9428-0c607c5eb182)

What OS do you use? Are you on Windows?

**Comment by GamingUnleashed** [comment]
yes

**Comment by LittlestCube** [comment]
Awesome, what do you plan to use it for? If you want to use it with Zelda64Recomp then you'll probably have to use [Visual Studio](https://visualstudio.microsoft.com/vs/community/) to build.

Once you have the installer pulled up, scroll down to Desktop & Mobile, and check Desktop development with C++.

Then, at the top next to Workloads, click on Individual Components. Search for cmake, and make sure C++ CMake tools for Windows is checked. Search again for clang, and make sure C++ Clang Compiler for Windows is checked. Then you can click the purple button in the bottom-right to install Visual Studio with what you need.

Once it installs, open Visual Studio and click Open a local folder on the right side. Find and open your N64Recomp folder.

Once Visual Studio opens, and you see `CMake generation finished.` at the bottom of the screen, click on Build > Build All.

After that, every exe you need should appear in N64Recomp/out/build/x64-Debug. 😋

**Comment by GamingUnleashed** [comment]
no i want to try it on super mario 64

**Comment by Mr-Wiseguy** [comment]
Based on #92 it sounds like you got the repo to build, so closing this issue.

**Comment by NiErUZMK94** [comment]
> Awesome, what do you plan to use it for? If you want to use it with Zelda64Recomp then you'll probably have to use [Visual Studio](https://visualstudio.microsoft.com/vs/community/) to build.
> 
> Once you have the installer pulled up, scroll down to Desktop & Mobile, and check Desktop development with C++.
> 
> Then, at the top next to Workloads, click on Individual Components. Search for cmake, and make sure C++ CMake tools for Windows is checked. Search again for clang, and make sure C++ Clang Compiler for Windows is checked. Then you can click the purple button in the bottom-right to install Visual Studio with what you need.
> 
> Once it installs, open Visual Studio and click Open a local folder on the right side. Find and open your N64Recomp folder.
> 
> Once Visual Studio opens, and you see `CMake generation finished.` at the bottom of the screen, click on Build > Build All.
> 
> After that, every exe you need should appear in N64Recomp/out/build/x64-Debug. 😋

Question, how to install "C++ Clang Compiler for Windows" on Visual Code Studio or etc.?
