### ISSUE TITLE
Error in Recompiling Function boot___osProbeTLB and Unhandled COP0 Register During N64 Recompilation

### ISSUE THREAD

**Issue by JamesAnthonyDellaMorte** [N64Recomp/N64Recomp#98]
During the recompilation of an N64 ROM using my banjo.toml configuration,  I got the:

```
./N64Recomp banjo.toml
Function count: 12427
Working dir: /Users/jamesdellamorte/N64Recomp/target
[Info] Ambiguous jal target 0x80387340 in function func_803531C8, falling back to function lookup
[Info] Ambiguous jal target 0x8038E2FC in function func_803531C8, falling back to function lookup
[Warn] Function boot_handle_CpU is branching outside of the function (to 0x80002774)
Tail call in boot_handle_CpU to 0x8000275C
Unhandled cop0 register in mfc0: 10
Error in recompiling boot___osProbeTLB, clearing output file
Error recompiling boot___osProbeTLB
```

Any insights on resolving the mfc0 COP0 register handling or the recompilation of boot___osProbeTLB would be appreciated.

[banjo.toml](https://github.com/user-attachments/files/17044707/banjo.txt)

**Comment by Mr-Wiseguy** [comment]
The `boot_` prefixed libultra functions in Banjo-Kazooie need to be ignored, as they're copies of the regular libultra functions (I'm the one who set that up in the decompilation). Those libultra functions either need to be reimplemented by the runtime or just stubbed out, since they're just used for loading the core1 codesegment. With that said, I figured that I should let you know that I'm already working on Banjo (the footage shown of this game in Nerrel's video is a recompilation of Banjo, not emulator footage).

**Comment by JamesAnthonyDellaMorte** [comment]
@Mr-Wiseguy Hey, thanks for the heads-up! I’ll ignore the `boot_` libultra functions and try reimplementing them as an exercise. Also, that’s awesome to hear! I’m mostly doing this to familiarize myself with the tool, I’m looking forward to seeing your work on Banjo!

**Comment by JamesAnthonyDellaMorte** [comment]
@Mr-Wiseguy Hey, thanks for the heads-up! I’ll ignore the boot_ libultra functions and try reimplementing them as an exercise. Also, that’s awesome to hear! I’m mostly doing this to familiarize myself with the tool, I’m looking forward to seeing your work on Banjo!

**Comment by Delta62Arcus** [comment]
@Mr-Wiseguy You said that you are currently working on Banjo. Is there somewhere we can follow progress for that specific recomp? I am interested in this specific recomp and ran into the same issue on this thread.

**Comment by snowboundmage2** [comment]
here's some help for the next person:

[input]
entrypoint = 0x80080000
output_func_path = "RecompiledFuncs"
elf_path = "banjo.us.v10.elf"
rom_file_path = "banjo.us.v10.z64"

[patches]
stubs = [
  "boot___osExceptionPreamble",
  "boot_handle_CpU",
  "boot___osProbeTLB",
  "boot_osMapTLBRdb",
  "boot___osException",
  "boot_osWritebackDCache",
  "boot___osDispatchThread",
  "func_8026A2E0",
  "osWriteBackDCacheAll",
  "boot_osInvalICache"
]
