### ISSUE TITLE
Steam legality

### ISSUE THREAD

**Issue by CCIGAMES** [N64Recomp/N64Recomp#99]
Would an old N64 game be able to go on steam if it was natively recompiled with N64Recomp? I was thinking Since N64Recomp relies on libultra as the primary lib that the games use, which belongs to Nintendo iirc. I've also been thinking if there was any sort of loophole to get Zelda64 on steam either as a steam workshop mod for an emulator that is already on there, or if the N64Recomp tool itself plus some custom code with no art or UI can go on there classed the same as an emulator, launcher, or tool, I would like my first question answered the most out of the 2, the second was just an unlikely afterthought since Steam could then hold the save and maybe even rom so we don't have to manually transfer between devices.

Thanks

**Comment by Mr-Wiseguy** [comment]
No, this will never happen.

**Comment by CCIGAMES** [comment]
> No, this will never happen 

My first question was about the developers of the original games, say for example the Croc remaster was built off of a recompiled version of Croc made with N64RECOMP, would that be legally OK to put on Steam?
